nexus_crm/nexus_crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls", namespace="users")),
    path('crm/', include("orders.urls", namespace="orders")),
    path('crm/', include("clients.urls", namespace="clients")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # Также добавим для staticfiles
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()

nexus_crm/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('registration/', views.SignUpUser.as_view(), name='registration' ),
    path('', views.LoginUser.as_view(), name='login' ),
    path('login/', views.LoginUser.as_view(), name='login' ),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(next_page='users:login'), name='logout'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    #  Инициация «одно-кликового» сброса пароля:
    path('password-reset-init/', views.PasswordResetInitiateView.as_view(), name='password_reset_init'),
    path('password-reset/<int:user_id>/<str:token>/', views.password_reset_confirm,name='password_reset_confirm'),

    # Сброс пароля на странице логина
    path('password-reset/',views.PasswordResetRequestView.as_view(),name='password_reset'),



]

nexus_crm/users/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.core.validators import RegexValidator
from django.utils import timezone

from users.manager import MyUserManager


# Create your models here.

class UserProfile(AbstractBaseUser):
    username = models.CharField(max_length=50, verbose_name="username", null=True, blank=False, unique=True)
    telegram_id = models.CharField(max_length=15, verbose_name="telegram",
                                   blank=True, null=True,
                                   default=None, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    photo = models.ImageField(
        upload_to='profile_photos/',
        verbose_name='Фото профиля',
        blank=True,
        null=True,
    )

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    phone_regex = RegexValidator(regex=r'^((\+7)|8)\d{10}$',
                                 message="Phone number must be entered in the format: '+79999999999' or '89999999999'.")
    phone_number = models.CharField(validators=[phone_regex], max_length=16, verbose_name="телефон", null=True,
                                    blank=True)

    email_notification = models.BooleanField(default=True, verbose_name="Оповещения на почту")
    telegram_notification = models.BooleanField(default=True, verbose_name="Оповещения в телеграм")
    day_off_notification = models.BooleanField(default=False, verbose_name="Оповещения по выходным")

    def __str__(self):
        return f"Профиль пользователя {self.username}"

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        db_table = "user_profile"
        verbose_name = "Профиль менеджера"
        verbose_name_plural = "Профили менеджеров"

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

nexus_crm/users/forms.py
from django import forms
from django.contrib.auth.forms import UsernameField, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.password_validation import password_validators_help_text_html, validate_password
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.forms.widgets import ClearableFileInput
from users.models import UserProfile


class SignUpForm(forms.ModelForm):
    username = forms.CharField(
        label=_("Имя пользователя"),
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    email = forms.EmailField(label=_("Email address"),
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text=_("Пароль должен содержать минимум 4 символа")

    )

    password2 = forms.CharField(
        label=_("Password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = UserProfile
        fields = ['username', 'email', 'phone_number']

    def clean_password2(self):
        """
        Проверка совпадения паролей.
        """
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("Passwords do not match."))
        validate_password(password1)
        return password2

    def save(self, commit=True):
        """
        Переопределяем метод save для сохранения пароля в хэшированном виде.
        """
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])  # Хэшируем пароль
        if commit:
            user.save()
        return user


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label=_("Email"),
        max_length=150,
        # help_text=_(
        #     "Letters, digits and @/./+/-/_ only."
        # ),
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text=_("Пароль должен содержать минимум 4 символа")

    )

    class Meta:
        model = UserProfile
        fields = ['username', 'password']


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(
        label=_("Имя пользователя"),
        max_length=150,

        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    email = forms.EmailField(label=_("Email address"),
                             widget=forms.TextInput(attrs={'class': 'form-control'}), )
    photo = forms.ImageField(
        required=False,
        widget=ClearableFileInput(attrs={'accept': 'image/*', 'id': 'id_photo'} ))

    class Meta:
        model = UserProfile
        fields = ['username', 'email', 'photo', ]

    def clean_photo(self):
        photo = self.cleaned_data.get('photo')
        if photo:
            if photo.size > 2 * 1024 * 1024:
                raise ValidationError("Максимальный размер фото — 2MB")
            if not photo.content_type.startswith('image/'):
                raise ValidationError("Загружать можно только изображения")
        return photo


# class PasswordResetRequestForm(forms.Form):
#     email = forms.EmailField(
#         label="Email",
#         max_length=50,
#         widget=forms.EmailInput(attrs={'class': 'input-register form-control',
#                                        'placeholder': 'Your email'})
#     )

class PasswordResetConfirmForm(forms.Form):
    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(attrs={'class': 'input-register form-control',
                                          'placeholder': 'New password'})
    )
    new_password2 = forms.CharField(
        label="Confirm New Password",
        widget=forms.PasswordInput(attrs={'class': 'input-register form-control',
                                          'placeholder': 'Confirm new password'})
    )

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user is None:
            raise ValueError("PasswordResetConfirmForm requires a `user` argument")
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')
        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data

    def save(self, commit=True):
        # если вы хотите здесь сохранять пароль — можно
        self.user.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.user.save()
        return self.user


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput(attrs={"class": "form-input"}), )
    new_password1 = forms.CharField(
        label="Новый пароль",
        widget=forms.PasswordInput(attrs={"class": "form-input"}),

    )
    new_password2 = forms.CharField(
        label=("Повтор нового пароля"),

        widget=forms.PasswordInput(attrs={"class": "form-input"}),
    )


class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField(
        label="Email",
        max_length=50,
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Ваш email'
        })
    )

nexus_crm/users/views.py
from django.contrib.auth import  login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordContextMixin
from django.views.generic import View, FormView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views.generic import CreateView, UpdateView, TemplateView
from django.contrib import messages

from users.forms import SignUpForm, LoginUserForm, ProfileUserForm, UserPasswordChangeForm, PasswordResetConfirmForm, \
    PasswordResetRequestForm
from users.models import UserProfile
from users.tasks import send_welcome_email, send_password_reset_email


class IndexView(TemplateView):
    template_name = "base/base.html"
    extra_context = {'title': 'Главная страница'}


class SignUpUser(CreateView):
    model = UserProfile
    form_class = SignUpForm
    success_url = reverse_lazy('orders:dashboard')
    template_name = 'users/registration.html'
    extra_context = {'title': 'Регистрация'}
    success_message = "Регистрация прошла успешно!"

    def form_valid(self, form):
        user = form.save()
        self.object = user
        send_welcome_email.delay(user.email, user.username)
        login(self.request, user)  # Автоматический вход
        return redirect(self.get_success_url())


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

    def get_success_url(self):
        url = self.get_redirect_url()
        if url:
            return url
        return reverse_lazy("orders:dashboard")

    def form_valid(self, form):
        return super().form_valid(form)

class ProfileUser(LoginRequiredMixin, UpdateView):
    model = UserProfile
    form_class = ProfileUserForm
    template_name = 'users/profile.html'

    extra_context = {
        'title': 'Профиль пользователя',
    }

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

class PasswordResetInitiateView(LoginRequiredMixin, View):
    """
    По заходу на этот урл шлём письмо на email авторизованного пользователя
    и сразу даём фидбек через messages.
    """
    def get(self, request, *args, **kwargs):
        user = request.user

        # Ставим задачу отправки письма:
        send_password_reset_email.delay(user.email, user.pk)

        # Flash-сообщение:
        messages.success(
            request,
            "Письмо со ссылкой для сброса пароля отправлено на ваш email."
        )
        # Редиректим обратно в профиль (или куда хотите):
        return redirect('users:profile')



def password_reset_confirm(request, user_id, token):
    try:
        # uid = force_str(urlsafe_base64_decode(uidb64)) # Если в базе id user по uid
        user = UserProfile.objects.get(pk=user_id)
    except (TypeError, ValueError, OverflowError, UserProfile.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if user is not None and default_token_generator.check_token(user, token):
            if request.method == 'POST':
                form = PasswordResetConfirmForm(request.POST, user=user)
                if form.is_valid():
                    form.save()  # установит новый пароль и сохранит user
                    messages.success(request, "Пароль успешно сброшен.")
                    return redirect('users:login')
            else:
                form = PasswordResetConfirmForm(user=user)

            return render(request, 'users/password_reset_confirm.html', {
                'form': form,
                'validlink': True
            })
    else:
        return render(request, 'users/password_reset_confirm.html', {'validlink': False})

class PasswordResetRequestView(FormView):
    """
    Форма «Забыли пароль?»: вводим email, при валидном email
    ставим задачу send_password_reset_email.delay(...)
    """
    template_name = 'users/password_reset_form.html'
    form_class = PasswordResetRequestForm
    success_url = reverse_lazy('users:password_reset_init')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        try:
            user = UserProfile.objects.get(email=email)
        except UserProfile.DoesNotExist:
            messages.info(
                self.request,
                "Если такой email зарегистрирован — на него будет выслана ссылка."
            )
        else:
            # ставим таск
            send_password_reset_email.delay(email, user.pk)
            messages.success(
                self.request,
                "Если такой email зарегистрирован — ссылка для сброса пароля уже в пути."
            )
        return super().form_valid(form)

nexus_crm/templates/users/login.html
{% extends "base/base.html" %}



{% block content %}
  <!-- Section: Design Block -->
<section class="text-center text-lg-start">
    <style>
        .cascading-right {
            margin-right: -50px;
        }

        @media (max-width: 991.98px) {
            .cascading-right {
                margin-right: 0;
            }
        }

        .form-card {
            max-width: 500px;
            margin: auto;
        }
    </style>

    <!-- Jumbotron -->
    <div class="container py-4">
        <div class="row g-0 align-items-center">
            <!-- Form Column -->
            <div class="col-lg-6 mb-5 mb-lg-0">
                <div class="card form-card cascading-right bg-body-tertiary shadow-5">
                    <div class="card-body p-5 text-center">
                        <h2 class="fw-bold mb-5">Login</h2>
                        <h1>Nexus Service Link</h1>
                <p>Пожалуйста <a href="{% url 'users:login' %}">Войдите</a> или <a href="{% url 'users:registration' %}">Зарегестрируйтесь</a> для доступа к файлам.</p>
                        <form method="post">
                            {% csrf_token %}
                             {% if form.errors %}
                            <div class="alert alert-danger">
                                {% for field, errors in form.errors.items %}
                                    {{ errors }}
                                {% endfor %}
                            </div>
                            {% endif %}

                            <div class="mb-4">
                                <label class="form-label" for="id_username">{{ form.username.label }}</label>
                                {{ form.username }}
                                {% if form.username.help_text %}
                                    <div class="form-text">{{ form.username.help_text }}</div>
                                {% endif %}
                            </div>

                            <div class="mb-4">
                                <label class="form-label" for="id_password">{{ form.password.label }}</label>
                                {{ form.password }}
                                {% if form.password.help_text %}
                                    <div class="form-text">{{ form.password.help_text }}</div>
                                {% endif %}
                            </div>

                            <div class="form-check d-flex justify-content-center mb-4">
                                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example33" checked />
                                <label class="form-check-label" for="form2Example33">
                                    Подписаться на новостную рассылку
                                </label>
                            </div>

                            <button type="submit" class="btn btn-primary btn-block mb-4">Войти</button>
                            <a type="submit" class="btn btn-primary btn-block mb-4" href="{% url 'users:password_reset' %}" >Forgot password?</a>

                            <div class="text-center">
<!--                                <p>or sign up with:</p>-->
                                <button type="button" class="btn btn-link btn-floating mx-1"><i class="fab fa-facebook-f"></i></button>
                                <button type="button" class="btn btn-link btn-floating mx-1"><i class="fab fa-google"></i></button>
                                <button type="button" class="btn btn-link btn-floating mx-1"><i class="fab fa-twitter"></i></button>
                                <button type="button" class="btn btn-link btn-floating mx-1"><i class="fab fa-github"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <!-- Image Column -->
            <div class="col-lg-6">
                <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" class="w-100 rounded-4 shadow-4" alt="Login illustration" />
            </div>
        </div>
    </div>
    <!-- Jumbotron -->
</section>
<!-- Section: Design Block -->
{% endblock %}

nexus_crm/templates/users/password_reset_confirm.html
{% extends 'base/base.html' %}

{% block title %}Reset Your Password{% endblock %}

{% block content %}
    <h1>Reset Your Password</h1>
    {% if validlink %}
        <p>Enter your new password below.</p>
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
        <form method="post" class="reg-form">
            {% csrf_token %}

            <div class="form-group">
                <label for="{{ form.new_password1.id_for_label }}">New Password</label>
                {{ form.new_password1 }}
                {% if form.new_password1.errors %}
                    <div class="error">{{ form.new_password1.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="{{ form.new_password2.id_for_label }}">Confirm New Password</label>
                {{ form.new_password2 }}
                {% if form.new_password2.errors %}
                    <div class="error">{{ form.new_password2.errors }}</div>
                {% endif %}
            </div>
            <button type="submit">Reset Password</button>
        </form>
    {% else %}
        <p>The password reset link is invalid or has expired. Please request a new one.</p>
        <a href="{% url 'users:password_reset_request' %}" class="link">Request New Link</a>
    {% endif %}
{% endblock %}

nexus_crm/templates/users/password_reset_form.html
{% extends "base/base.html" %}
{% block content %}
  <h1>Забыли пароль?</h1>
  <form method="post">{% csrf_token %}
    {{ form.email.label_tag }}<br>
    {{ form.email }}<br><br>
    <button type="submit" class="btn btn-primary">Отправить ссылку</button>
  </form>
{% endblock %}

nexus_crm/templates/users/registration.html
{% extends "base/base.html" %}

{% block content %}

  <!-- Section: Design Block -->
<section class="text-center text-lg-start">
  <style>
    .cascading-right {
      margin-right: -50px;
    }

    @media (max-width: 991.98px) {
      .cascading-right {
        margin-right: 0;
      }
    }
  </style>

  <!-- Jumbotron -->
  <div class="container py-4">
    <div class="row g-0 align-items-center">
      <div class="col-lg-6 mb-5 mb-lg-0">
        <div class="card cascading-right bg-body-tertiary" style="
            backdrop-filter: blur(30px);
            ">
          <div class="card-body p-5 shadow-5 text-center">
            <h2 class="fw-bold mb-5">Sign up now</h2>
            <div class="text-center">
                <h1>Nexus Service Link</h1>
                <p>Пожалуйста <a href="{% url 'users:login' %}">войдите</a> для доступа к файлам.</p>
            </div>
            <form method="post">
              <!-- 2 column grid layout with text inputs for the first and last names -->

                        {% csrf_token %}
              {% if form.errors %}
                <div class="alert alert-danger">
                    {% for field, errors in form.errors.items %}
                        {{ errors }}
                    {% endfor %}
                </div>
                {% endif %}


              <div class="row">
                <div class="col-md-6 mb-4">
                  <div data-mdb-input-init class="form-outline">
                    <label class="form-label" for="id_username">{{ form.username.label }}</label>
                      {{ form.username }}
                    {% if form.username.help_text %}
                        <div class="form-text">{{ form.username.help_text }}</div>
                    {% endif %}
                  </div>
                </div>

                    <!-- Email input -->
                <div class="col-md-6 mb-4">
                  <div data-mdb-input-init class="form-outline">
                    <label class="form-label" for="id_email">{{ form.email.label }}</label>
                {{ form.email }}
                  </div>
                </div>
              </div>


              <!-- Password input -->
              <div class="mb-4">
                <label class="form-label" for="id_password1">{{ form.password1.label }}</label>
                {{ form.password1 }}
                {% if form.password1.help_text %}
                    <div class="form-text">{{ form.password1.help_text }}</div>
                {% endif %}
              </div>

              <div class="mb-4">
                <label class="form-label" for="id_password2">{{ form.password2.label }}</label>
                {{ form.password2 }}
                {% if form.password2.help_text %}
                    <div class="form-text">{{ form.password2.help_text }}</div>
                {% endif %}
               </div>


              <!-- Submit button -->
              <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">
                Регистрация
              </button>

              <!-- Register buttons -->
              <div class="text-center">
<!--                <p>or sign up with:</p>-->
                <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-facebook-f"></i>
                </button>

                <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-google"></i>
                </button>

                <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-twitter"></i>
                </button>

                <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-github"></i>
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>

      <div class="col-lg-6 mb-5 mb-lg-0">
        <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" class="w-100 rounded-4 shadow-4"
          alt="" />
      </div>
    </div>
  </div>
  <!-- Jumbotron -->
</section>
<!-- Section: Design Block -->


{% endblock%}